### WBB Notebook

```{r}
library(tidyverse)
```

### Z-Scores

```{r}
gamelogs <- read_csv("https://dwillis.github.io/sports-data-files/wbblogs24.csv")
```

```{r}
teamquality <- gamelogs |> 
  select(Conference, Team, TeamFGPCT, TeamTotalRebounds, OpponentFGPCT, OpponentTotalRebounds)
```

```{r}
teamtotals <- teamquality |> 
  filter(!is.na(OpponentFGPCT)) |>
  group_by(Conference, Team) |> 
  summarise(
    FGAvg = mean(TeamFGPCT), 
    ReboundAvg = mean(TeamTotalRebounds), 
    OppFGAvg = mean(OpponentFGPCT),
    OffRebAvg = mean(OpponentTotalRebounds)
    ) 
```

```{r}
teamzscore <- teamtotals |> 
  mutate(
    FGzscore = as.numeric(scale(FGAvg, center = TRUE, scale = TRUE)),
    RebZscore = as.numeric(scale(ReboundAvg, center = TRUE, scale = TRUE)),
    OppZscore = as.numeric(scale(OppFGAvg, center = TRUE, scale = TRUE)) * -1,
    OppRebZScore = as.numeric(scale(OffRebAvg, center = TRUE, scale = TRUE)) * -1,
    TotalZscore = FGzscore + RebZscore + OppZscore + OppRebZScore
  )  
```


```{r}
teamzscore |> arrange(desc(TotalZscore))
```

```{r}
teamzscore |> 
  filter(Conference == "Big Ten WBB") |> 
  arrange(desc(TotalZscore)) |>
  select(Team, TotalZscore)
```

```{r}
powerfive_plus_one <- c("SEC WBB", "Big Ten WBB", "Pac-12 WBB", "Big 12 WBB", "ACC WBB", "Big East WBB")
teamzscore |> 
  filter(Conference %in% powerfive_plus_one) |> 
  arrange(desc(TotalZscore)) |>
  select(Team, TotalZscore)
```



###Step Charts

```{r}
library(tidyverse)

logs <- read_csv("https://dwillis.github.io/sports-data-files/wbblogs24.csv")
```

```{r}
difflogs <- logs |> 
  mutate(Differential = TeamScore - OpponentScore) |> 
  group_by(TeamFullName) |> 
  mutate(CumDiff = cumsum(Differential))
```

```{r}
bigdiff <- difflogs |> filter(Conference == "Big Ten WBB")
```

```{r}
ggplot() + geom_step(data=bigdiff, aes(x=Date, y=CumDiff, group=Team))
```

```{r}
ggplot() + geom_step(data=bigdiff, aes(x=Date, y=CumDiff, group=Team, color=Team))
```


```{r}
umd <- bigdiff |> filter(Team == "Maryland")
ill <- bigdiff |> filter(Team == "Illinois")
```

```{r}
ggplot() + 
  geom_step(data=bigdiff, aes(x=Date, y=CumDiff, group=Team), color="light grey") +
  geom_step(data=umd, aes(x=Date, y=CumDiff, group=Team), color="red") + 
  geom_step(data=ill, aes(x=Date, y=CumDiff, group=Team), color="orange") +
  annotate("text", x=(as.Date("2023-12-10")), y=180, label="Illinois") +
  annotate("text", x=(as.Date("2024-02-01")), y=50, label="Maryland") +
  labs(
    x="Date", 
    y="Cumulative Point Differential", 
    title="Maryland's Uphill Climb, Illinois Hits Plateau", 
    subtitle="The Terps were middle of the pack in point differential.", 
    caption="Source: Sports-Reference.com | By Derek Willis") +
  theme_minimal()
```



###Early Season Data - Simple Rating
```{r}
library(tidyverse)
teams <- read_csv("https://dwillis.github.io/sports-data-files/wbbstats25.csv")
```

```{r}
library(ggrepel)

umd <- teams |> filter(School == "Maryland")

unbeated <- teams |> filter(OverallLosses == 0)

big_ten <- unbeated |> filter(School %in% c('Illinois', 'Indiana', 'Iowa', 'Michigan', 'Michigan State', 'Ohio State', 'Minnesota', 'Nebraska', 'Northwestern', 'Rutgers', 'Southern California', 'UCLA', 'Oregon', 'Washington', 'Maryland'))

avg_srs <- unbeated |> filter(!is.na(OverallSRS)) |>
  summarise(mean(OverallSRS)) |> pull(1)

avg_sos <- unbeated |> filter(!is.na(OverallSOS)) |>
  summarise(mean(OverallSOS)) |> pull(1)

ggplot() +
  geom_point(data=unbeated, aes(x=OverallSRS, y=OverallSOS, size = OverallWins), color = "grey") +
  geom_point(data=big_ten, aes(x=OverallSRS, y=OverallSOS, size = OverallWins), color = "yellow") +
  geom_point(data=umd, aes(x=OverallSRS, y=OverallSOS, size = OverallWins), color = "red") +
  geom_vline(xintercept = avg_srs) +
  geom_hline(yintercept = avg_sos) +
  geom_text_repel(
    data=big_ten, 
    aes(x=OverallSRS, y=OverallSOS, label=School)
  )
```

